name: Code Formatter

on:
  push:
    branches:
    - gh-pages

jobs:
  formatter:

    name: Standard Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Checking out Repository
      uses: actions/checkout@v2.3.4
      with:
        ref: gh-pages
    - name: Setting up node.js
      uses: actions/setup-node@v2.1.4
      with:
        node-version: '12'
    - name: Installing dependencies
      run: npm install
    - name: Run Auto Formatter
      run: npm run standard
