name: System Test

on:
  push:
    branches:
    - gh-pages

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out Repository
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Setup Java Action
      uses: actions/setup-java@v1.0.0
      with:
        version: 1.8
    - name: Setting up node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Installing dependencies
      run: npm install
    - name: Executing Tests
      run: npm run test
      env:
        JSON_CONFIG: ${{ secrets.JSON_CONFIG }}
